/**
 * lib/venues/injectVenueIds.ts
 *
 * ------------------------------------------------------------------
 * Purpose
 * ------------------------------------------------------------------
 * Loads environment variables from .env.local
 * Matches curated NYC venue slugs to Supabase `venues` table
 * Injects `id` into curated NYC venue data
 * Writes a fixed TypeScript file: data/nyc.ts
 *
 * Usage:
 *   npx tsx lib/venues/injectVenueIds.ts
 */

import * as dotenv from 'dotenv'
import fs from 'fs'
import path from 'path'
import { createClient } from '@supabase/supabase-js'

/* ------------------------------------------------------------------ */
/* LOAD ENVIRONMENT CONFIG                                            */
/* ------------------------------------------------------------------ */

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') })
dotenv.config()

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
  throw new Error(
    'Missing Supabase env vars. Ensure NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are set in .env.local'
  )
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY)

/* ------------------------------------------------------------------ */
/* TYPES                                                              */
/* ------------------------------------------------------------------ */

type BaseVenue = {
  slug: string
  name: string
  [key: string]: any
}

type SupabaseVenue = {
  id: string
  slug: string
}

/* ------------------------------------------------------------------ */
/* MAIN SCRIPT                                                        */
/* ------------------------------------------------------------------ */

async function runInjection() {
  // Force NYC, no args
  const city = 'nyc'
  console.log(`\n🔧 Running venue ID injection for NYC\n`)

  const baseDataPath = path.join(process.cwd(), 'data', 'base', `${city}.json`)
  const outputPath = path.join(process.cwd(), 'data', 'nyc.ts')

  console.log(`• Base JSON expected at: ${baseDataPath}`)
  console.log(`• Output TS file will be: ${outputPath}`)

  if (!fs.existsSync(baseDataPath)) {
    throw new Error(`Base data file not found: ${baseDataPath}`)
  }

  const raw = fs.readFileSync(baseDataPath, 'utf-8')
  if (!raw.trim()) {
    throw new Error(`Base JSON is empty: ${baseDataPath}`)
  }

  let baseVenues: BaseVenue[]
  try {
    baseVenues = JSON.parse(raw)
  } catch (e) {
    throw new Error(`Failed to parse base JSON: ${(e as Error).message}`)
  }

  console.log(`📄 Loaded ${baseVenues.length} curated venues from NYC JSON`)

  const { data: supabaseVenues, error } = await supabase
    .from('venues')
    .select('id, slug')

  if (error || !supabaseVenues) {
    throw new Error(`Supabase fetch failed: ${error?.message}`)
  }

  console.log(`🗄️  Loaded ${supabaseVenues.length} venues from Supabase`)

  const venueMap = new Map<string, SupabaseVenue>()
  supabaseVenues.forEach((v) => venueMap.set(v.slug, v))

  let matched = 0
  const unmatched: string[] = []

  const merged = baseVenues.map((venue) => {
    const match = venueMap.get(venue.slug)
    if (!match) {
      unmatched.push(venue.slug)
      return venue
    }
    matched++
    return { ...venue, id: match.id }
  })

  const fileContents = `/**
 * ⚠️ AUTO-GENERATED FILE
 * Do NOT edit manually.
 * Generated by lib/venues/injectVenueIds.ts
 */

import type { Venue } from '@/types/venue'

const venues: Venue[] = ${JSON.stringify(merged, null, 2)}

export default venues
`

  fs.writeFileSync(outputPath, fileContents)
  console.log(`\n✅ Injection complete`)
  console.log(`   ✔ Matched: ${matched}`)
  console.log(`   ⚠ Unmatched: ${unmatched.length}`)

  if (unmatched.length > 0) {
    console.warn('\n⚠ Unmatched slugs:')
    unmatched.slice(0, 30).forEach((slug) => console.warn(`   - ${slug}`))
    if (unmatched.length > 30) {
      console.warn(`   ...and ${unmatched.length - 30} more`)
    }
  }

  // Confirm the file now exists & print first few lines
  const exists = fs.existsSync(outputPath)
  console.log(`\nFile exists? ${exists ? 'YES' : 'NO'}`)

  if (exists) {
    const snippet = fs.readFileSync(outputPath, 'utf-8').split('\n').slice(0, 15)
    console.log('\n--- output snippet ---')
    snippet.forEach((line) => console.log(line))
    console.log('--- end snippet ---\n')
  }
}

/* ------------------------------------------------------------------ */
/* RUN                                                              */
/* ------------------------------------------------------------------ */
runInjection().catch((err) => {
  console.error('\n❌ Injection failed:', err)
  process.exit(1)
})
